name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      PORT: 3000
      JWT_SECRET: your-jwt-secret
      MONGO_URL: mongodb://localhost/rezsi-io
      GMAIL_USER: your-gmail-address
      GMAIL_PASS: your-gmail-password
      GMAIL_ADDRESS: your-gmail-address
      CLIENT_ORIGIN: http://localhost:3001

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.4.0'
    - run: npm ci
    - run: npm test
